apiVersion: apps/v1
kind: Deployment
metadata:
  name: manageblue-projects-microservice
  labels:
    app: manageblue-projects-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manageblue-projects-microservice
  template:
    metadata:
      labels:
        app: manageblue-projects-microservice
    spec:
      containers:
      - name: manageblue-projects-microservice
        image: ghcr.io/manageblue/manageblue-microservice-projects:latest
        env:
        - name: MONGODB_CLOUD_URI
          value: "mongodb+srv://ManageBlueMongo:MBM-pass-420@managebluemongo.wxj1o.mongodb.net/ManageBlue"
        ports:
        - containerPort: 5001

---

apiVersion: v1
kind: Service
metadata:
  name: manageblue-projects-microservice-load-balancer
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5001
  selector:
    app: manageblue-projects-microservice
