apiVersion: apps/v1
kind: Deployment
metadata:
  name: manageblue-projects-microservice
  labels:
    app: manageblue-projects-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manageblue-projects-microservice
  template:
    metadata:
      labels:
        app: manageblue-projects-microservice
    spec:
      containers:
      - name: manageblue-projects-microservice
        image: ghcr.io/manageblue/manageblue-microservice-projects:latest
        env:
          - name: MONGODB_CLOUD_URI
            value: mongodb+srv://ManageBlueMongo:RSOmongo420@managebluemongo.wxj1o.mongodb.net/ManageBlueMongo
          - name: TASK_API
            value: manageblue-tasks-microservice-load-balancer.default.svc.cluster.local/
          - name: TASK_API2
            value: manageblue-tasks-microservice-load-balancer/api/v1/tasks2
        ports:
        - containerPort: 5001

---

apiVersion: v1
kind: Service
metadata:
  name: manageblue-projects-microservice-node-port
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5001
  selector:
    app: manageblue-projects-microservice
